import pandas as pd
import numpy as np
import os
import time 

from pdf_extracter.text_module import *
from pdf_extracter.image_module import *
from file_utils import *



def disagreement_resolution(test_folder, model, model_key, agreement_filepath):

    files_in_folder = os.listdir(test_folder)
    df = pd.read_excel(agreement_filepath)

    variables = df["Variable"]
    gr = df["GPT_Responses"]
    cr = df["CLAUDE_Responses"]
    gs = df["Gold_Standard"]
    ad = df["Agree(A)/Disagree(D)"]
    
    files = df["File"]
    for i in range(files.shape[0]):
        # files[i] = files[i].replace("'","")
        if ".pdf" not in files[i]:
            files[i] += ".pdf"        
    files = files.values.tolist()

    chunk_start = 46000
    chunk_end = 45000

    allresponses_list = []

    os.makedirs("Images_AD", exist_ok=True) # create directory to store images
    image_foldername = os.getcwd() + "/Images_AD/" # super-folder path where images of each file will be stored into sub-folders
    count=0
    
    for i in range(len(cr)):

        if ad[i] == "D": # Disagreement Check
            file = files[i]    # get the filename
            if file in files_in_folder: # file exist in folder
                print (file, "\t" ,count, "\n")
                count+=1

                # Prompt Design
                var = str(variables[i])
                if model == "claude":
                    val = str(gr[i])
                else:
                    val = str(cr[i])
                p = "For the given text, LLM generate the response = [" + val + "] for the variable = [" + var + "]. Verify if the response for the given variable generated by LLM is correct or incorrect. If the response is incorrect, then generate the correct response (as short and precise as possible)."

                pdffile_path = test_folder + "/" + file

                pdftext = extract_text_from_pdf(pdffile_path) # extracting text from pdf            
                tokens_list = get_tokens(pdftext, "cl100k_base", chunk_start, chunk_end) # comment this line for previous version

                encoding = tiktoken.get_encoding("cl100k_base")
                tokens2 = encoding.encode(pdftext) # encode the text into tokens

                print ("Extracted Tokens:", len(tokens2),"\nExtracted Chunks:", len(tokens_list),"\n")

                allresponses = "File Name: " + file + "\n"
                allresponses += "Variable Name: " + var + "\n"
                allresponses += "Gold Standard: " + str(gs[i]) + "\n"
                allresponses += "GPT Response: " + str(gr[i]) + "\n"
                allresponses += "Claude Response: " + str(cr[i]) + "\n\n"
                allresponses += "Verification from the Text...\n"

                for t in tokens_list: # iterate over all the chunks of a document f

                    if model == "claude":
                        response = claude_function(t, p, model_key, model)
                        response = str(response)
                        time.sleep(30) # to avoid TPM limit
                    else:
                        response = gpt_function(t, p, model_key, model)

                    allresponses = allresponses + "\n" + response # concatenate responces of all prompts for a single chunk of text


                # image extraction from pdf
                os.makedirs(image_foldername + file, exist_ok=True) # sub_directory to store the images of a particular pdf
                extract_images_from_pdf_2(pdffile_path, image_foldername + file) # function call to extract images from a pdf_file

                images = os.listdir(image_foldername + file) # get names of all images from the folder
                print ("Extracted Images:",len(images))
                allresponses = allresponses + "\n\n" + "Verification from the images..."

                for img in images:

                    print (" - Images are in Process...")

                    image_path = image_foldername + file + "/" + img # get image path    

                    if "claude" in model:
                        image_result = image_processing_claude(p, image_path, model_key, model)
                        image_result = str(image_result)
                        time.sleep(20) # to avoid TPM limit
                    else:
                        image_result = image_processing_gpt(p, image_path, model_key) # call GPT here
                        time.sleep(10)

                    allresponses = allresponses + "\n\n" + image_result # concatenate responces of all prompts for a single chunk of text
                print ("\n")

                allresponses_list.append(allresponses) # allresponses = output of one pdf

    ff = "DisagreementResolution_by_"+model            
    write_raw_responses(allresponses_list, ff) # change file name for claude